#!/bin/bash

# Default config var
LIBREI_VERSION="0.6.16"
LIBREI_DEBUG_DEFAULT=true
LIBREI_REQUIREMENTS_CENTOS="git curl jq docker"
ANSIBLE_RPM_FILENAME="ansible-2.7.9-1.el7.ans.noarch.rpm"
ANSIBLE_RPM_URL="https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/${ANSIBLE_RPM_FILENAME}"
TMP_DEST=/tmp/libre
INSTALLER_BIN=/usr/local/bin/installer-libre
ANSIBLE_DEST=/usr/local/lib/libre-ansible
INSTALLER_URL=https://goo.gl/T8Dw9J
THIS_SCRIPT="$(realpath $0)"

# config var
LIBRE_TOOLREPO_URL=https://github.com/startxfr/libre
LIBRE_TOOLREPO_BRANCH=master
LIBRE_TOOLREPO_BASE=/

# default command line options
LIBRE_TYPE=instructor
UPDATE=n
ASK_BECOME_PASS=

# get and store the operating system name
source /etc/os-release
OS="$NAME"
OS_NAME="$PRETTY_NAME"

# use only our Ansible config
unset ANSIBLE_CONFIG

# use xterm
export TERM=xterm


if [[ "$LIBREI_DEBUG" == true || "$LIBREI_DEBUG" == "true" || "$LIBREI_DEBUG" == "True" || "$LIBREI_DEBUG" == false || "$LIBREI_DEBUG" == "false" || "$LIBREI_DEBUG" == "False" ]] ; then
  LBI_DEBUG=$LIBREI_DEBUG
else
  LBI_DEBUG=$LIBREI_DEBUG_DEFAULT
fi
# return if debug is activated
function isDebug {
    if [[ "$LBI_DEBUG" == true || "$LBI_DEBUG" == "true" || "$LBI_DEBUG" == "True" ]] ; then
        return 1
    else
        return 0
    fi
}

# echo if debug if activated
function echoDebug {
    if [[ "$LBI_DEBUG" == true || "$LBI_DEBUG" == "true" || "$LBI_DEBUG" == "True"  ]] ; then
        echo "$@"
    fi
}

# echo an error
function echoError {
    echo "  ERROR ! $@"
}

# echo an error and exit
function echoFatal {
    echo "  FATAL ! $@"
    exit 1;
}

# echo an error and exit
function echoWarn {
    echo "  WARN  ! $@"
}

# echo an error and exit
function echoOK {
    echo "SUCCESS : $@"
}

# check for super-user identity
if [ "$(id -u)" != "0" ]; then
    echoError "This script must be run as root or you must have sudo"
    echoError "Try to execute 'sudo -i' and run again this command"
    exit 1
fi

# Display libre installer header
function print_header {
    cat <<-'BANNER'
	  _     _ _                    _           _        _ _
	 | |   (_) |__  _ __ ___      (_)_ __  ___| |_ __ _| | | ___ _ __
	 | |   | | '_ \| '__/ _ \_____| | '_ \/ __| __/ _` | | |/ _ \ '__|
	 | |___| | |_) | | |  __/_____| | | | \__ \ || (_| | | |  __/ |  
	 |_____|_|_.__/|_|  \___|     |_|_| |_|___/\__\__,_|_|_|\___|_|

	BANNER
}

# Display information
function print_info {
    print_header
    echo "installer : v$LIBREI_VERSION"
    isDebug
    if [ "$?" -eq 1 ] ; then
      echo "repo      : $LIBRE_TOOLREPO_URL"
      echo "branch    : $LIBRE_TOOLREPO_BRANCH"
      echo "base      : $LIBRE_TOOLREPO_BASE"
    else
      echo "libre-src : $LIBRE_TOOLREPO_URL @$LIBRE_TOOLREPO_BRANCH$LIBRE_TOOLREPO_BASE"
    fi
    echo "OS        : $OS_NAME"
    echo "host      : $HOSTNAME"
    echo "type      : $LIBRE_TYPE"
    echo
}

function check_type {
    [ $# -eq 1 ] || {
        return 1
    }

    local types=(instructor student)

    for t in "${types[@]}"; do
        [ "$1" == "$t" ] && return 0
    done

    return 2
}

function prep_dir {
    [ $# -eq 1 ] || {
        return 1
    }
    local dir="$1"

    #if [ -w $dir/.. ]; then
    #    rm -rf $dir
    #    echoOK "Remove previous $dir directory"
    #fi

    mkdir -p "$dir" &> /dev/null || {
        echoError "Unable to create $dir"
        return 2
    }
    if [ ! -w "$dir" ]; then
        echoError "$dir is not writable"
        return 3
    fi

    return 0
}

# Display information
function prep_env {
    if [ ! -f $INSTALLER_BIN ]; then
        rm -rf $INSTALLER_BIN
        install -T -m 0755 -o root -g root "$THIS_SCRIPT" $INSTALLER_BIN
    fi

    prep_dir $TMP_DEST     &&
    prep_dir $ANSIBLE_DEST || exit 1

    return 0
}

# installer update system
function install_deps {
    if [ "$UPDATE" == "y" ]; then
        echo "Updating OS $OS installation (cloud take minutes...)"
        yum update -y &> /dev/null
    fi
    if [ ! -f /tmp/libre-is-updated ]; then
      echo "Removing package PyYAML"
      (
          yum remove -y PyYAML # it will be reinstalled with yq
      ) &> /dev/null                                 || {
          echoFatal "Unable to uninstall PyYAML"
      }
      echo "Download Ansible RPM file"
      (
	  curl -L $ANSIBLE_RPM_URL  -o /tmp/${ANSIBLE_RPM_FILENAME} &&
	  chmod +x /tmp/${ANSIBLE_RPM_FILENAME}
      ) &> /dev/null                                 || {
          echoFatal "Unable to download Ansible RPM file"
      }
      # epel and python-pip packages must be installed separately,
      # otherwise pip does not settle, probably a yum bug
      echo "Installing packages for $OS (could take minutes on fresh install or slow internet)"
      (
          yum install -y epel-release python-pip &&
          pip install --upgrade --force-reinstall pip==9.0.3 &&
          pip install --upgrade docker		     &&
          yum remove -y python-pip               &&
          yum install -y python-pip              &&
          pip install --upgrade pip              &&
          pip install --upgrade yq               &&
          pip install --upgrade Jinja2		     &&
          yum install -y $LIBREI_REQUIREMENTS_CENTOS &&
	  yum install -y /tmp/${ANSIBLE_RPM_FILENAME} 
      ) &> /dev/null                                 || {
          echoFatal "Unable to install dependencies"
      }
      touch /tmp/libre-is-updated
    else 
      echo "Skip updating packages because /tmp/libre-is-updated is found"
    fi
}

# installer install libre
function fetch_installer {
    pushd $TMP_DEST &> /dev/null
    echo "Clone tools repository $LIBRE_TOOLREPO_URL"
    isDebug
    if [ "$?" -eq 1 ] ; then
        git clone $LIBRE_TOOLREPO_URL .
    else
        git clone $LIBRE_TOOLREPO_URL . &> /dev/null
    fi
    if [ "$?" -eq 0 ]; then
        echo "Change branch for $LIBRE_TOOLREPO_BRANCH"
        isDebug
        if [ "$?" -eq 1 ] ; then
	    git checkout $LIBRE_TOOLREPO_BRANCH
        else
            git checkout $LIBRE_TOOLREPO_BRANCH &> /dev/null
        fi
        echo "Copy libre playbook into $ANSIBLE_DEST"
        cp -r $TMP_DEST$LIBRE_TOOLREPO_BASE/ansible/* $ANSIBLE_DEST/
    fi
    popd &> /dev/null
}

# installer install libre
function clean_installer {
    echo "Remove $TMP_DEST"
    rm -rf $TMP_DEST
}

# installer check post-installation
function check_installation {
    if [ ! -d $ANSIBLE_DEST ]; then
        echoFatal "$ANSIBLE_DEST doesn't exist"
    fi
}

# installer installation process
function install_libre {
    print_info
    perform_installation

    pushd $ANSIBLE_DEST &> /dev/null

    echo "Start $LIBRE_TYPE installation"
    isDebug
    if [ "$?" -eq 1 ] ; then
        ansible-playbook $ASK_BECOME_PASS playbooks/$LIBRE_TYPE/install.yml
    else
        ansible-playbook $ASK_BECOME_PASS playbooks/$LIBRE_TYPE/install.yml &> /dev/null
    fi
    if [ "$?" -eq 0 ]; then
	    echo "Reload bash profile"
	    source /etc/profile.d/libre.sh &> /dev/null
	    echo -e $(cat /tmp/libre.txt)
	    if [[ "$LIBRE_TYPE" == "instructor" && "$IS_INTERACTIVE" == "yes" ]]; then
	      read -p "Do you want to continue by installing training session (y/N) : " doInstall
	      if [[ "$doInstall" == "y" || "$doInstall" == "yes" ]]; then
		    libre-session install
	        echo -e $(cat /tmp/libre.txt)
	      fi
	    else
		  echoOK "You can continue by running libre-session install"
	    fi
    else
	  echo -e $(cat /tmp/libre.txt)
        echoError "libre $LIBRE_TYPE installation failed to completed"
        echoError "try to run again ./libre-installer install $LIBRE_TYPE"
        echoError "or report bug to support team"
        exit 1;
    fi
    popd &> /dev/null
}

# do installation process
function perform_installation {
    prep_env
    install_deps
    fetch_installer
    clean_installer
    check_installation
}

# installer uninstall process
function uninstall_libre {
    print_info
    perform_uninstallation
}

# do uninstall process
function perform_uninstallation {
    if [ -d $ANSIBLE_DEST ]; then
        pushd $ANSIBLE_DEST &> /dev/null
        ansible-playbook playbooks/$LIBRE_TYPE/uninstall.yml
        popd &> /dev/null
    fi
}

# reinstaller remove libre environement
function reinstall_libre {
    print_info
    perform_uninstallation
    echo "Refresh installer-libre"
    rm -f $INSTALLER_BIN
    curl -s -L $INSTALLER_URL -o $INSTALLER_BIN &> /dev/null
    chmod +x $INSTALLER_BIN
    $INSTALLER_BIN install $LIBRE_TYPE
}

# Display installer usage
function print_usage {
    print_header 
    cat <<-EOF
	Startx Formation training environment installer

	Usage:
	  $0 sub-command [-t INSTALL_TYPE] [-Kiu] [command]

	Options:
	     -t INSTALL_TYPE  install LIBRE_TYPE training environment
	                      INSTALL_TYPE can be one of:
	                                                    - instructor (default)
	                                                    - student
	     -K               prompt for Ansible's privilege escalation password
	     -i               interactive and prompt for session setup on instructor post-install 
	     -u               fully update the system during installation

	Availables sub-commands:
	     install          install LIBRE TMS and instructor or student training
	                      environment (interactive)
	     uninstall        uninstall LIBRE TMS and training environment
	     reinstall        re-install LIBRE TMS and training environment
	EOF
}

while getopts :Kt:u c; do
    case "$c" in
        K)
            ASK_BECOME_PASS="-K"
            ;;
        i)
            IS_INTERACTIVE="yes"
            ;;
        t)
            check_type "$OPTARG" || {
                echoError "Invalid argument for option -t : $OPTARG"
                print_usage
                exit 1
            }
            LIBRE_TYPE="$OPTARG"
            ;;
        u)
            UPDATE=y
            ;;
        '?')
            echoError "Unsupported option : -$OPTARG"
            print_usage
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

# Dispatch input arguments
case "$1" in
    "install")        install_libre ;;
    "uninstall")      uninstall_libre ;;
    "reinstall")      reinstall_libre ;;
    *)                print_usage ;;
esac
