#!/bin/bash

source /usr/local/lib/libre-core

# Display session header message
function sessionHeader {
  isVerbose
  if [ "$?" -eq 1 ] ; then
    cat /usr/local/lib/libre-session.txt
  fi
}

# Call session playbook without checking that session is installed
function sessionFreePlaybook {
  sessionHeader
  runLibrePlaybook session $1 $2
  exit 0;
}

# Call session playbook
function sessionPlaybook {
  sessionHeader
  checkIfSession
  runLibrePlaybook session $1 $2
  exit 0;
}

# Call session install playbook
function sessionInstallPlaybook {
  sessionHeader
  param="local"
  if [[ $2 != "" ]] ; then
    param="$param -e session_id=$2";
  fi
  if [[ $3 != "" ]] ; then
    param="$param -e session_token=$3";
  fi
  runLibrePlaybook session $1 $param
  exit 0;
}

# Display session info and exit
function sessionInformation {
  sessionHeader
  coreInformation
  exit 0;
}

# Display session welcome and exit
function sessionWelcome {
  sessionHeader
  coreInformation
  echoEnv
  sessionUsage
  exit 0;
}

# Display version info and exit
function sessionVersion {
  coreVersion
  exit 0;
}

# Display libre-session usage
function sessionUsage {
cat <<EOF

Instructor session training management command line.

Usage:
  libre-session [command]

- Generic commands:
  config           configure session environment
  install          install session environment
  start            start training session
  stop             stop training session
  uninstall        uninstall session environment
  status           get status of the current session
  history          get history of the session actions
  usage            get command line usage information
  info             give information about current libre installation
  version          give information about current libre version
EOF
}


